language: go
sudo: false
go_import_path: periph.io/x/periph
go:
 - 1.8
script:
 - touch coverage.txt
 - bash -c 'for d in $(go list ./...); do go test -coverprofile=p.out $d; if [ -f p.out ]; then cat p.out >> coverage.txt; rm p.out; fi; done'
after_success:
 - bash <(curl -s https://codecov.io/bash)
